version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.21
    - 0.20.22
    - 0.20.23
    - 0.20.24
    - 0.20.25
    - 0.20.26
    - 0.20.27
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.31
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: typescript
    versions:
    - 4.0.6
